const publishers = [
  "Aurum Publishing House",
  "Briarwood Books",
  "Cairnstone Press",
  "Davenport Publishing Co.",
  "Eclipse Editions",
  "Fablewood Books",
  "Gideon Press",
  "Havenstead Publishing",
  "Ironwood Books",
  "Jasper & Co.",
  "Kairos Publishing Group",
  "Luminari Press",
  "Maverick Books",
  "Nexus Publishing House",
  "Oxford Bridge Press",
  "Pinnacle Books",
  "Quill & Quire",
  "Raven's Peak Publishing",
  "Sagebrook Press",
  "Terra Nova Books",
  "Umbra Publishing Co.",
  "Vespera Press",
  "Waverley Books",
  "Xanadu Publishing House",
  "Yalebrook Press",
  "Zephyr Books",
  "Asterion Publishing",
  "Bramble & Co.",
  "Cedarwood Press",
  "Dunbar Publishing",
  "Elysian Books",
  "Falconer Press",
  "Garnet Publishing Co.",
  "Haven Books",
  "Ivybrook Publishing",
  "Journey's End Press",
  "Kestrel Books",
  "Larkspur Publishing",
  "Meadowbrook Press",
  "Nightingale Books",
  "Oriel Publishing Co.",
  "Parchment Press",
  "Quincy Publishing",
  "Ridgeview Books",
  "Savannah Publishing",
  "Talbot Press",
  "Upton Publishing Co.",
  "Vikinga Books",
  "Windsor Publishing House",
  "Xylon Press",
];
