interface IBook {
  title: string;
  author: string;
  year: string;
}

export interface IGenre {
  genreName: string;
  data: IBook[];
}
const romance: IGenre = {
  genreName: "Romance",
  data: [
    { title: "Jane Eyre", author: "Charlotte Brontë", year: "1847" },
    { title: "Wuthering Heights", author: "Emily Brontë", year: "1847" },
    { title: "The Princess Bride", author: "William Goldman", year: "1973" },
    {
      title: "The Bridges of Madison County",
      author: "Robert James Waller",
      year: "1992",
    },
    { title: "The Rosie Project", author: "Graeme Simsion", year: "2013" },
    {
      title: "Eleanor Oliphant is Completely Fine",
      author: "Gail Honeyman",
      year: "2017",
    },
    { title: "Me Before You", author: "Jojo Moyes", year: "2012" },
    { title: "The Fault in Our Stars", author: "John Green", year: "2012" },
    { title: "Attachments", author: "Rainbow Rowell", year: "2010" },
    {
      title: "The Royal We",
      author: "Heather Cocks and Jessica Morgan",
      year: "2015",
    },
    { title: "The Wedding Date", author: "Jasmine Guillory", year: "2018" },
    { title: "The Wedding Party", author: "Jasmine Guillory", year: "2019" },
    { title: "The Honey-Don't List", author: "Christina Lauren", year: "2020" },
    { title: "Well Met", author: "Jen DeLuca", year: "2019" },
    { title: "Get a Life, Chloe Brown", author: "Talia Hibbert", year: "2019" },
    { title: "The Wedding Pact", author: "Katee Robert", year: "2019" },
    { title: "Sweet Disaster", author: "Abbi Glines", year: "2016" },
    { title: "Wait for It", author: "Molly O'Keefe", year: "2016" },
    {
      title: "The Wall of Winnipeg and Me",
      author: "Mariana Zapata",
      year: "2016",
    },
    { title: "From Lukov with Love", author: "Mariana Zapata", year: "2018" },
    { title: "Kulti", author: "Mariana Zapata", year: "2015" },
    { title: "The Simple Wild", author: "K.A. Tucker", year: "2018" },
    { title: "The Great Alone", author: "Kristin Hannah", year: "2018" },
    { title: "The Identicals", author: "Elin Hilderbrand", year: "2017" },
    { title: "The Royal Runaway", author: "Lindsay Emory", year: "2018" },
    { title: "The Governess Game", author: "Tessa Dare", year: "2018" },
    {
      title: "The Lady's Guide to Petticoats and Piracy",
      author: "Mackenzi Lee",
      year: "2018",
    },
    { title: "An American Marriage", author: "Tayari Jones", year: "2018" },
    {
      title: "The Seven Husbands of Evelyn Hugo",
      author: "Taylor Jenkins Reid",
      year: "2017",
    },
    {
      title: "The Last Letter from Your Lover",
      author: "Jojo Moyes",
      year: "2012",
    },
    { title: "The Girl You Left Behind", author: "Jojo Moyes", year: "2012" },
    { title: "Me After You", author: "Jojo Moyes", year: "2015" },
    { title: "After You", author: "Jojo Moyes", year: "2015" },
    { title: "Still Me", author: "Jojo Moyes", year: "2018" },
    { title: "The Bronze Horseman", author: "Paullina Simons", year: "2000" },
    { title: "Tatiana and Alexander", author: "Paullina Simons", year: "2003" },
    { title: "The Summer Garden", author: "Paullina Simons", year: "2006" },
    {
      title: "The Bronze Horseman Trilogy",
      author: "Paullina Simons",
      year: "2000",
    },
    {
      title: "The Age of Miracles",
      author: "Karen Thompson Walker",
      year: "2012",
    },
    {
      title: "The Particular Sadness of Lemon Cake",
      author: "Aimee Bender",
      year: "2010",
    },
    { title: "The First Bad Man", author: "Miranda July", year: "2015" },
    { title: "The Vacationers", author: "Emma Straub", year: "2014" },
    { title: "Modern Lovers", author: "Emma Straub", year: "2016" },
    { title: "The Interestings", author: "Meg Wolitzer", year: "2013" },
    { title: "The Female Persuasion", author: "Meg Wolitzer", year: "2018" },
    {
      title: "Conversations with Friends",
      author: "Sally Rooney",
      year: "2017",
    },
    { title: "Normal People", author: "Sally Rooney", year: "2018" },
    { title: "The Mothers", author: "Brit Bennett", year: "2016" },
    { title: "The Idiot", author: "Elif Batuman", year: "2017" },
    { title: "The New Me", author: "Halle Butler", year: "2019" },
    { title: "The Wedding", author: "Nicholas Sparks", year: "2003" },
    { title: "The Bride", author: "Julie Garwood", year: "1989" },
    { title: "The Duchess Deal", author: "Tessa Dare", year: "2017" },
    { title: "The Kiss Quotient", author: "Helen Hoang", year: "2018" },
    { title: "Love in the Afternoon", author: "Lisa Kleypas", year: "2010" },
    {
      title: "The French Lieutenant's Woman",
      author: "John Fowles",
      year: "1969",
    },
    { title: "Love Story", author: "Erich Segal", year: "1970" },
    { title: "The Notebook", author: "Nicholas Sparks", year: "1996" },
    { title: "Outlander", author: "Diana Gabaldon", year: "1991" },
    { title: "Gone with the Wind", author: "Margaret Mitchell", year: "1936" },
    { title: "The Thorn Birds", author: "Colleen McCullough", year: "1977" },
    { title: "The Duchess", author: "Danielle Steel", year: "1987" },
    { title: "The Bridegroom", author: "Ha Jin", year: "2000" },
    { title: "Love Walks In", author: "Samantha Chase", year: "2015" },
    { title: "The Viscount Who Loved Me", author: "Julia Quinn", year: "2002" },
    {
      title: "The Notebook of Trigorin",
      author: "John Van Druten",
      year: "1949",
    },
    { title: "The Love Letter", author: "Lucinda Riley", year: "2022" },
    {
      title: "The French Mistress",
      author: "Susan Holloway Scott",
      year: "2014",
    },
    { title: "Embrace Me", author: "Lisa Samson", year: "2006" },
    { title: "The Bride's Awakening", author: "Caitlin Crews", year: "2013" },
    { title: "The French Bride", author: "Robin Bridges", year: "2017" },
    { title: "The Hating Game", author: "Talia Hibbert", year: "2018" },
    { title: "The Proposal", author: "Anthea Lawson", year: "2013" },
    { title: "The Duchess War", author: "Courtney Milan", year: "2012" },
    { title: "The Bride Test", author: "Adelia Saunders", year: "2019" },
    { title: "The Kiss", author: "Danielle Steel", year: "2007" },
    {
      title: "Love in the Time of Cholera",
      author: "Gabriel García Márquez",
      year: "1985",
    },
    { title: "Pride and Prejudice", author: "Jane Austen", year: "1813" },
    {
      title: "The Time Traveler's Wife",
      author: "Audrey Niffenegger",
      year: "2013",
    },
    { title: "The Duke and I", author: "Julia Quinn", year: "2010" },
  ],
};
export default romance;
