interface IBook {
  title: string;
  author: string;
  year: string;
}
export const thrillers: IBook[] = [
  { title: "Psycho", author: "Robert Bloch", year: "1959" },
  { title: "The Silence of the Lambs", author: "Thomas Harris", year: "1988" },
  {
    title: "The Girl with the Dragon Tattoo",
    author: "Stieg Larsson",
    year: "2005",
  },
  { title: "The Da Vinci Code", author: "Dan Brown", year: "2003" },
  { title: "The Bourne Identity", author: "Robert Ludlum", year: "1980" },
  { title: "Gone Girl", author: "Gillian Flynn", year: "2012" },
  { title: "Sharp Objects", author: "Gillian Flynn", year: "2006" },
  { title: "The Woman in the Window", author: "A.J. Finn", year: "2018" },
  { title: "The Last Mrs. Parrish", author: "Liv Constantine", year: "2017" },
  { title: "The Couple Next Door", author: "Shari Lapena", year: "2016" },
  { title: "The Lincoln Rhyme", author: "by Jeffery Deaver", year: "1999" },
  { title: "The Cuckoo's Calling", author: "Robert Galbraith", year: "2013" },
  { title: "The Devil in the White City", author: "Erik Larson", year: "2003" },
  { title: "The Poison Tree", author: "Erin Kelly", year: "2010" },
  { title: "The Devil's Teardrop", author: "Jeffery Deaver", year: "1999" },
  { title: "The Girl on the Train", author: "Paula Hawkins", year: "2015" },
  { title: "The Woman in Cabin 10", author: "Ruth Ware", year: "2016" },
  {
    title: "The 7 1/2 Deaths of Evelyn Hardcastle",
    author: "Stuart Turton",
    year: "2018",
  },
  { title: "The Last Time I Lied", author: "Riley Sager", year: "2018" },
  { title: "The Other Mrs. Miller", author: "Allison Dickson", year: "2019" },
  { title: "The Bourne Series", author: "Robert Ludlum", year: "1980" },
  { title: "The Jack Reacher Series", author: "Lee Child", year: "1997" },
  { title: "The Mitch Rapp Series", author: "Vince Flynn", year: "1999" },
  { title: "The Gray Man Series", author: "Mark Greaney", year: "2009" },
  { title: "The Sigma Force Series", author: "James Rollins", year: "2004" },
  { title: "The Name of the Rose", author: "Umberto Eco", year: "1980" },
  { title: "The Alienist", author: "Caleb Carr", year: "1994" },
  { title: "The Historian", author: "Elizabeth Kostova", year: "2005" },
  {
    title: "The Shadow of the Wind",
    author: "Carlos Ruiz Zafón",
    year: "2001",
  },
  { title: "The Dante Club", author: "Matthew Pearl", year: "2003" },
  { title: "The Silent Patient", author: "Alex Michaelides", year: "2019" },
  { title: "The Last House Guest", author: "Megan Miranda", year: "2019" },
  { title: "The Stranger Diaries", author: "Elly Griffiths", year: "2019" },
  { title: "The Family Upstairs", author: "Lisa Jewell", year: "2019" },
  { title: "The Chain", author: "Adrian McKinty", year: "2019" },
  { title: "The Inspector Morse Series", author: "Colin Dexter", year: "1975" },
  { title: "The Harry Hole Series", author: "Jo Nesbo", year: "1997" },
  { title: "The Wallander Series", author: "Henning Mankell", year: "1991" },
  {
    title: "The Kay Scarpetta Series",
    author: "Patricia Cornwell",
    year: "1990",
  },
  { title: "The Alex Cross Series", author: "James Patterson", year: "1993" },
  { title: "The Shining", author: "Stephen King", year: "1977" },
  { title: "The Exorcist", author: "William Peter Blatty", year: "1971" },
  { title: "The Amityville Horror", author: "Jay Anson", year: "1977" },
  { title: "The Fisherman", author: "John Langan", year: "2016" },
  { title: "The Hunger", author: "Alma Katsu", year: "2018" },
  {
    title: "The Wife Between Us",
    author: "Greer Hendricks and Sarah Pekkanen",
    year: "2018",
  },
  { title: "The Last Mrs. Parrish", author: "Liv Constantine", year: "2017" },
  { title: "The Wife's Revenge", author: "Kerry Kaya", year: "2019" },
  { title: "The Family Next Door", author: "Sally Hepworth", year: "2018" },
  { title: "The Other Woman", author: "Sandie Jones", year: "2018" },
  { title: "The Last Time I Saw You", author: "Liv Constantine", year: "2019" },
  { title: "The Other People", author: "C.J. Tudor", year: "2019" },
  { title: "The Stranger Inside", author: "Lisa Unger", year: "2019" },
  { title: "The 17th Suspect", author: "James Patterson", year: "2018" },
  { title: "The Witch Elm", author: "Tana French", year: "2018" },
  { title: "The Devil's Highway", author: "Ken Bruen", year: "2019" },
  { title: "The Poison Tree", author: "Erin Kelly", year: "2010" },
  { title: "The Bone Collector", author: "Jeffery Deaver", year: "1997" },
  { title: "The Cutting Edge", author: "Jeffery Deaver", year: "1999" },
  { title: "The Devil's Star", author: "Jo Nesbo", year: "2003" },
  { title: "The Invited", author: "Jennifer McMahon", year: "2019" },
  { title: "The Stranger Diaries", author: "Elly Griffiths", year: "2019" },
  { title: "The Last House Guest", author: "Megan Miranda", year: "2019" },
  { title: "The Family Upstairs", author: "Lisa Jewell", year: "2019" },
  { title: "The Chain", author: "Adrian McKinty", year: "2019" },
  {
    title: "The Gray Ghost",
    author: "Clive Cussler and Robin Burcell",
    year: "2018",
  },
  { title: "The 14th Colony", author: "Steve Berry", year: "2016" },
  { title: "The Spy Who Came Home", author: "H.K. Roy", year: "2018" },
  { title: "The Enemy of My Enemy", author: "Mark Greaney", year: "2019" },
  { title: "The Deceivers", author: "Alex Berenson", year: "2019" },
  { title: "The Historian", author: "Elizabeth Kostova", year: "2005" },
  { title: "The Dante Club", author: "Matthew Pearl", year: "2003" },
  { title: "The Alienist", author: "Caleb Carr", year: "1994" },
  {
    title: "The Shadow of the Wind",
    author: "Carlos Ruiz Zafón",
    year: "2001",
  },
  { title: "The Name of the Rose", author: "Umberto Eco", year: "1980" },
  { title: "The Silent Patient", author: "Alex Michaelides", year: "2019" },
  { title: "The Last House Guest", author: "Megan Miranda", year: "2019" },
  { title: "The Stranger Diaries", author: "Elly Griffiths", year: "2019" },
  { title: "The Family Upstairs", author: "Lisa Jewell", year: "2019" },
  { title: "The Chain", author: "Adrian McKinty", year: "2019" },
  { title: "The 7th Woman", author: "Frédérique Molay", year: "2015" },
  { title: "The Darkness", author: "Ragnar Jónasson", year: "2018" },
  { title: "The Blind", author: "A.F. Brady", year: "2017" },
  { title: "The Poison Tree", author: "Erin Kelly", year: "2010" },
  { title: "The Bone Collector", author: "Jeffery Deaver", year: "1997" },
  { title: "The Fisherman", author: "John Langan", year: "2016" },
  { title: "The Hunger", author: "Alma Katsu", year: "2018" },
  { title: "The Rust Maidens", author: "Gwendolyn Kiste", year: "2018" },
  { title: "The Devil Crept In", author: "Ania Ahlborn", year: "2017" },
  { title: "The Border", author: "Robert R. McCammon", year: "2015" },
  { title: "The Wife's Revenge", author: "Kerry Kaya", year: "2019" },
  { title: "The Family Next Door", author: "Sally Hepworth", year: "2018" },
  { title: "The Other Woman", author: "Sandie Jones", year: "2018" },
  {
    title: "The Wife Between Us",
    author: "Greer Hendricks and Sarah Pekkanen",
    year: "2018",
  },
  { title: "The Last Mrs. Parrish", author: "Liv Constantine", year: "2017" },
  { title: "The Girl on the Train", author: "Paula Hawkins", year: "2015" },
  { title: "The Woman in the Window", author: "A.J. Finn", year: "2018" },
  { title: "The Silent Companions", author: "Laura Purcell", year: "2017" },
  { title: "The Poison Tree", author: "Erin Kelly", year: "2010" },
  { title: "The Blind", author: "A.F. Brady", year: "2017" },
];
